#!/bin/sh

# Note: We check the connection then allow the commands to execute (This is required only for initial setup

export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_ROOT_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"

mysql_ready() {
python << END
import sys

import _mysql
print('At python init entry point script')
try:
    _mysql.connect(
        db="${MYSQL_DATABASE}",
        user="${MYSQL_USER}",
        passwd="${MYSQL_ROOT_PASSWORD}",
        host="${MYSQL_HOST}",
        port=${MYSQL_PORT},
    )
except Exception as e:
    print('Exception', e)
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for Mysql......'
  sleep 1
done
>&2 echo 'Mysql init and inter container connection successful'

exec "$@"
